Models/Stock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MultiUserMVC.Models
{
    public class Stock
    {
        [Key]
        public int Id { get; set; }

        public string Symbol { set; get; }
        public string Last_Price { set; get; }
        public string Change { set; get; }
        public string Change_Percentage { set; get; }
        public string Currency { set; get; }
        public string Market_Time { set; get; }
        public string Volume { set; get; }
        public string Average_Volume { set; get; }
        public string Market_Cap { set; get; }
        public string ScrapeDate { set; get; }

    }
}

Controllers/StocksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiUserMVC.Models;
namespace MultiUserMVC.Controllers
{
    public class StocksController : Controller
    {
        private readonly ApplicationDBContext _db;

        public StocksController(ApplicationDBContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Stock Stock { get; set; }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Stock = new Stock();
            if (id == null)
            {
                //Create
                return View(Stock);
            }

            //Update
            Stock = _db.Stocks.FirstOrDefault(u => u.Id == id);
            if (Stock == null)
            {
                return NotFound();
            }
            return View(Stock);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Scrape()
        {

            var scraper = new Scraper();

            scraper.saveStocks();

            //Pushes changes to database
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Stocks.ToListAsync() });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var stockFromDb = await _db.Stocks.FirstOrDefaultAsync(u => u.Id == id);
            if (stockFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.Stocks.Remove(stockFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion
    }
}

Views/Stocks/Index.cshtml
@using MultiUserMVC.Areas.Identity.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <br />
    <div class="container row p-0 m-0">
        <div class="col-6">
            <h2 class="text-info">Stocks</h2>
        </div>
        <div class="col-3 offset-3">
            <form method="post">
                <button type="submit" asp-controller="Stocks" asp-action="Scrape" class="btn btn-info form-control text-white" id="btnload">Update Stocks</button>
            </form>
        </div>
        <div class="col-12 border p-3">

            <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Symbol</th>
                        <th>Last Price</th>
                        <th>Change</th>
                        <th>Change Percentage</th>
                        <th>Currency</th>
                        <th>Market Time</th>
                        <th>Volume</th>
                        <th>Average Volume</th>
                        <th>Market Cap</th>
                        <th>Date of Record</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
}
else
{
    <div class="text-center">
        <h1 class="display-4">Stocks</h1>

        <p> Create an account and/or login to view current and past stock data.</p>
    </div>

}

@section Scripts{
    <script src="~/js/stockList.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#btnload').click(async function () {
                $(await this).html('<img src="http://www.bba-reman.com/images/fbloader.gif" />');
                return false;
            });
        })
    </script>
}

Views/Stocks/Upsert.cshtml
@model MultiUserMVC.Models.Stock

<br />
<h2 class="text-info"> Update Stock</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Symbol"></label>
            </div>
            <div class="col-6">
                <input asp-for="Symbol" class="form-control" />
                <span asp-validation-for="Symbol" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Last_Price"></label>
            </div>
            <div class="col-6">
                <input asp-for="Last_Price" class="form-control" />
                <span asp-validation-for="Last_Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Change"></label>
            </div>
            <div class="col-6">
                <input asp-for="Change" class="form-control" />
                <span asp-validation-for="Change" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Change_Percentage"></label>
            </div>
            <div class="col-6">
                <input asp-for="Change_Percentage" class="form-control" />
                <span asp-validation-for="Change_Percentage" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Currency"></label>
            </div>
            <div class="col-6">
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Market_Time"></label>
            </div>
            <div class="col-6">
                <input asp-for="Market_Time" class="form-control" />
                <span asp-validation-for="Market_Time" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Volume"></label>
            </div>
            <div class="col-6">
                <input asp-for="Volume" class="form-control" />
                <span asp-validation-for="Volume" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Average_Volume"></label>
            </div>
            <div class="col-6">
                <input asp-for="Average_Volume" class="form-control" />
                <span asp-validation-for="Average_Volume" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Market_Cap"></label>
            </div>
            <div class="col-6">
                <input asp-for="Market_Cap" class="form-control" />
                <span asp-validation-for="Market_Cap" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ScrapeDate"></label>
            </div>
            <div class="col-6">
                <input asp-for="ScrapeDate" class="form-control" />
                <span asp-validation-for="ScrapeDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id != 0 ? "Update" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}